In [1]:
from tensorflow import keras

import pandas as pd
from pandas import Series, DataFrame
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier

from keras.utils import np_utils

In [3]:
train=pd.read_csv('sample_training_data.csv')
train.head()

,Year,Target Country,Source Country,Import Value,Commodity,Weather Index,GDP,GRI,BP1,BP2,BP3
0,2012,India,China,618158,38,0.01,0.4,0.16,0.6,0.1,0.7
1,2012,India,United States of America,708143,38,0.01,0.4,0.16,0.6,0.1,0.7
2,2012,India,Indonesia,124367,38,0.01,0.4,0.16,0.6,0.1,0.7
3,2012,India,Germany,297607,38,0.01,0.4,0.16,0.6,0.1,0.7
4,2012,India,Singapore,129580,38,0.01,0.4,0.16,0.6,0.1,0.7

In [4]:
X = train[['Year','Target Country','Source Country', 'Import Value', 'Commodity', 'Weather Index', 'GDP', 'GRI']][:]
y = train[['BP1','BP2','BP3']][:]

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=104, test_size=0.33, shuffle=False)

In [39]:
from sklearn.preprocessing import LabelEncoder

enc = LabelEncoder()

source_df = enc.fit_transform(X_train['Source Country'])
target_df = enc.fit_transform(X_train['Target Country'])

source_test_df = enc.fit_transform(X_test['Source Country'])
target_test_df = enc.fit_transform(X_test['Target Country'])

X_train.head()

X_train.drop(['Target Country', 'Source Country'], axis=1)
X_train['Source Country'] = source_df
X_train['Target Country'] = target_df

X_test.drop(['Target Country', 'Source Country'], axis=1)
X_test['Source Country'] = source_test_df
X_test['Target Country'] = target_test_df

# sdf = X_train.join(new_df)

X_train.head()

# print(enc.inverse_transform(new_df))

,Year,Target Country,Source Country,Import Value,Commodity,Weather Index,GDP,GRI
0,2012,0,32,618158,38,0.01,0.4,0.16
1,2012,0,155,708143,38,0.01,0.4,0.16
2,2012,0,69,124367,38,0.01,0.4,0.16
3,2012,0,58,297607,38,0.01,0.4,0.16
4,2012,0,133,129580,38,0.01,0.4,0.16

In [44]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.multioutput import MultiOutputClassifier
from sklearn.linear_model import LogisticRegression


# clf = MultiOutputClassifier(LogisticRegression()).fit(X, y)

clf=DecisionTreeRegressor(max_depth=3)
clf.fit(X_train,y_train)
clf.score(X_test,y_test)*100

# mlp=MLPClassifier(hidden_layer_sizes=(163,), max_iter=100, solver='adam', learning_rate_init=0.1 )

# X_train=np_utils.to_categorical(X_train['Target Country'])

# mlp.fit(X_train,y_train)

# prediction=mlp.predict(X_test)

# print(prediction)

100.0